kind: pipeline
name: default

# Pipeline for putting cloudformation files into S3 for nested stacks
steps:
  - name: docker push
    image: plugins/docker
    settings:
      repo: eignhpants/drone-tests
      username:
        from_secret: dh_user_name
      password:
        from_secret: dh_pw
    publish:
      image: eignhpants/sheeta
